// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaOlr0l8h_yWFlBwpctmOgDhCFPpVuYGk',
    appId: '1:1067083310608:web:39fc1ee8e40403bf80cc95',
    messagingSenderId: '1067083310608',
    projectId: 'gigivet22firebase',
    authDomain: 'gigivet22firebase.firebaseapp.com',
    storageBucket: 'gigivet22firebase.appspot.com',
    measurementId: 'G-GGV76T2Y64',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeHWlk1TNaGmnadDoSo1nyLbwe3zvMREc',
    appId: '1:1067083310608:android:580f9e74b7daf28f80cc95',
    messagingSenderId: '1067083310608',
    projectId: 'gigivet22firebase',
    storageBucket: 'gigivet22firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk_cluKjkCnds2v4b8yGLRMf1odw3eX90',
    appId: '1:1067083310608:ios:9cd162cdfe462abc80cc95',
    messagingSenderId: '1067083310608',
    projectId: 'gigivet22firebase',
    storageBucket: 'gigivet22firebase.appspot.com',
    iosClientId: '1067083310608-8kqc0deldv51dsf7n2dmbfga0a15l2oh.apps.googleusercontent.com',
    iosBundleId: 'com.example.gigivet22firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDk_cluKjkCnds2v4b8yGLRMf1odw3eX90',
    appId: '1:1067083310608:ios:9cd162cdfe462abc80cc95',
    messagingSenderId: '1067083310608',
    projectId: 'gigivet22firebase',
    storageBucket: 'gigivet22firebase.appspot.com',
    iosClientId: '1067083310608-8kqc0deldv51dsf7n2dmbfga0a15l2oh.apps.googleusercontent.com',
    iosBundleId: 'com.example.gigivet22firebase',
  );
}
